sudo: false
language: python
python:
  - "2.7"
  - "3.4"
virtualenv:
  system_site_packages: true

addons:
  apt:
    packages:
      - dnsutils    # for dig command in /script/cibuild
      - golang-go   # for akamai cli packages

before_install:
  - openssl aes-256-cbc -K $encrypted_47d2d923bf7d_key -iv $encrypted_47d2d923bf7d_iv -in edgerc.txt.enc -out .edgerc -d

before_script:
  - chmod +x ./script/cibuild

script: ./script/cibuild

before_deploy:
  - curl -L https://github.com/akamai/cli-purge/releases/download/1.0.0/akamai-purge-1.0.0-linuxamd64 -o akamai-purge
  - chmod +x akamai-purge
  - export PATH=$PATH:$PWD

deploy:
  - provider: script
    skip_cleanup: true
    script: echo "Hello"
    on:
      branch: master

after_deploy:
  - |
    akamai-purge --edgerc .edgerc --section travis delete --cpcode 490267
